In [10]:
import pandas as pd
import pymongo

df = pd.read_csv('data.csv')
df.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [11]:
# df should be converted to a dictionary before inserting into MongoDB
data = df.to_dict(orient='records')

In [21]:
DB_NAME = "Proj1"
COLLECTION_NAME = "Proj1-Data"
CONNECTION_URL = "mongodb+srv://aanamishra2407_db_user:PGnkgZfiJJXDUjye@cluster0.rtfdy77.mongodb.net/?appName=Cluster0"



# above, either remove your credentials or delete the mongoDB resource bofore pushing it to github.

In [22]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [23]:
# Upload data to MongoDB
rec = collection.insert_many(data)

print(f"Inserted {len(rec.inserted_ids)} records")

Inserted 381109 records

In [24]:
print(type(rec))

<class 'pymongo.results.InsertManyResult'>

In [25]:
records = collection.find()
records

In [26]:
# Load back data from mongodb

df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,6aa9286083045041e5940013,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,6aa9286083045041e5940014,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0

In [ ]:
## If you are getting timeout issue

# import certifi
# client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())
# # TO CREATE THE DATABASE
# data_base = client[DB_NAME]
# collection = data_base[COLLECTION_NAME]
# # TO INSERT DATA INTO THE COLLECTION
# rec = collection.insert_many(data)